version: '3.5'
services:
  db:
    build: postgresql
    image: taskmanager_postgresql:1.0.0
    restart: always

    environment:
      POSTGRES_USER: task_manager
      POSTGRES_PASSWORD: q1w2e3r4
    networks:
      - taskmanager_ntwrk
  pgadmin:
    build: pgadmin
    image: taskmanager_pgadmin:1.0.0
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "82:80"
    networks:
      - taskmanager_ntwrk

  swagger-ui:
    build: swagger-ui
    image: taskmanager_swagger-ui:1.0.0
    ports:
      - "81:8080"
    networks:
      - taskmanager_ntwrk

  user-service:
    build: user-service
    image: taskmanager_user-service:1.0.0
    networks:
      - taskmanager_ntwrk

  audit-service:
    build: audit-service
    image: taskmanager_audit-service:1.0.0
    networks:
      - taskmanager_ntwrk

  task-service:
    build: task-service
    image: taskmanager_task-service:1.0.0
    networks:
      - taskmanager_ntwrk

  report-service:
    build: report-service
    image: taskmanager_report-service:1.0.0
    networks:
      - taskmanager_ntwrk

  proxy:
    build: proxy
    image: taskmanager_proxy:1.0.0
    ports:
      - "80:80"
    networks:
      - taskmanager_ntwrk

  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    networks:
      - taskmanager_ntwrk

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - taskmanager_ntwrk

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - taskmanager_ntwrk

networks:
  taskmanager_ntwrk:
    name: taskmanager_ntwrk