spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/audit_service?ApplicationName=audit-service
    username: audit_service
    password: q1w2e3r4
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_schema: app
logging:
  level:
    org.springframework.web: DEBUG

