spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/audit_service?ApplicationName=audit-service
    username: audit_service
    password: q1w2e3r4
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_schema: app
  kafka:
    consumer:
      group-id: app.1
    bootstrap-server: localhost:9092
#  jackson:
#    deserialization:
#      trusted:
#        packages: by.it_academy.task_manager_common.dto
logging:
  level:
    org.springframework.web: DEBUG
jwt:
  secret: IjudckibNeWw0CzOuxn6YtQMGs3bsry2M534Fl7F/us=
  issuer: Kirill
feign:
  user:
    url: http://user-service:8080/users

