spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/audit_service?ApplicationName=audit-service
  kafka:
    bootstrap-server: localhost:9092
  rabbitmq:
    host: localhost
server:
  port: 92
feign:
  user:
    url: http://localhost:91/users
