spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/TaskManagerUser
    username: task_manager
    password: q1w2e3r4
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_schema: app
  mail:
    host: smtp.gmail.com
    port: 587
    username: testovich061@gmail.com
    password: dfzmovdbupqiwccb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 80
logging:
  level:
    org.springframework.web: DEBUG

