spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/TaskManagerUser
    username: task_manager
    password: q1w2e3r4
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_schema: app
server:
  port: 80