spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/user_service?ApplicationName=user-service
    username: user_service
    password: q1w2e3r4
#  flyway:
#    baseline-on-migrate: true
#    enable: true
#    user: user_service
#    password: q1w2e3r4
#    schemas: app
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_schema: app
  mail:
    host: smtp.gmail.com
    port: 587
    username: testovich061@gmail.com
    password: dfzmovdbupqiwccb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    consumer:
      group-id: app.1
    bootstrap-server: kafka:9092
  rabbitmq:
    userAuditQueue: userAuditQueue
    host: rabbitmq
logging:
  level:
    org.springframework.web: DEBUG
server:
  port: 8080
app:
  verification:
    url: http://localhost/api/v1/users/verification
feign:
  audit:
    url: http://audit-service:8080/audit
jwt:
  secret: IjudckibNeWw0CzOuxn6YtQMGs3bsry2M534Fl7F/us=
  issuer: Kirill


