spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_service?ApplicationName=user-service
  kafka:
    bootstrap-server: localhost:9092
server:
  port: 93
feign:
  user:
    url: http://localhost:91/users
  audit:
    url: http://localhost:92/audit