spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/task_service?ApplicationName=task-service
    username: task_service
    password: q1w2e3r4
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_schema: app
logging:
  level:
    org.springframework.web: DEBUG
server:
  port: 8080
jwt:
  secret: IjudckibNeWw0CzOuxn6YtQMGs3bsry2M534Fl7F/us=
  issuer: Kirill
feign:
  user:
    url: http://user-service:8080/users
  audit:
    url: http://audit-service:8080/audit
  okhttp:
    enabled: true