spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_service?ApplicationName=user-service
server:
  port: 93
feign:
  user:
    url: http://user-service:91/users
  audit:
    url: http://audit-service:92/audit